AVR32: update init.d in target_skeleton for AVR32 boards
Signed-off-by: Hans-Christian Egtvedt <hans-christian.egtvedt@atmel.com>

diff --git a/target/device/Atmel/atstk1002/target_skeleton/etc/init.d/K90localfs b/target/device/Atmel/atstk1002/target_skeleton/etc/init.d/K90localfs
--- a/target/device/Atmel/atstk1002/target_skeleton/etc/init.d/K90localfs
+++ b/target/device/Atmel/atstk1002/target_skeleton/etc/init.d/K90localfs
@@ -1,1 +1,11 @@
 #!/bin/sh
+
+UMOUNT=/bin/umount
+
+echo -n "Unmounting local filesystems: "
+if ${UMOUNT} -a -r; then
+	echo "done"
+else
+	echo "failed"
+	exit 1
+fi
