Update target_skeleton for ATSTK1000 target device
This patch adds proper configuration files for the applications running by
default on the ATSTK1000.

It also updates all init.d scripts to match the output generated by buildroot
default init.d scripts.

Signed-off-by: Hans-Christian Egtvedt <hcegtvedt@atmel.com>

diff --git a/target/device/Atmel/ATSTK1000/target_skeleton/etc/init.d/S02hostname b/target/device/Atmel/ATSTK1000/target_skeleton/etc/init.d/S02hostname
--- a/target/device/Atmel/ATSTK1000/target_skeleton/etc/init.d/S02hostname
+++ b/target/device/Atmel/ATSTK1000/target_skeleton/etc/init.d/S02hostname
@@ -1,12 +1,9 @@
 #!/bin/sh
 
-HOSTNAME=`which hostname`
+PROGRAM=/bin/hostname
 
-echo -n " * setting hostname ...          "
-if [ ! -x "${HOSTNAME}" ]; then
-	echo "[ MISSING ]"
-	exit 1
-fi
+echo -n "Setting hostname:"
+[ -x ${PROGRAM} ] || (echo " missing"; exit 0)
 
 if [ -f /etc/hostname ]; then
 	HOST="$(cat /etc/hostname)"
@@ -14,12 +11,37 @@ else
 	HOST="localhost.localdomain"
 fi
 
-if ${HOSTNAME} "${HOST}" > /dev/null 2> /dev/null; then
-	echo "'${HOST}'"
-else
-	echo "[ FAILED ]"
-	exit 1
-fi
+start() {
+	if ${PROGRAM} "${HOST}" > /dev/null 2> /dev/null; then
+		echo " '${HOST}'"
+	else
+		echo " failed"
+		exit 1
+	fi
+}
 
-exit 0
+stop() {
+	return 0
+}
 
+restart() {
+	stop
+	start
+}
+
+case "$1" in
+  start)
+        start
+        ;;
+  stop)
+        stop
+        ;;
+  restart|reload)
+        restart
+        ;;
+  *)
+        echo $"Usage: $0 {start|stop|restart}"
+        exit 1
+esac
+
+exit $?
diff --git a/target/device/Atmel/ATSTK1000/target_skeleton/etc/init.d/S43ntp b/target/device/Atmel/ATSTK1000/target_skeleton/etc/init.d/S43ntp
--- a/target/device/Atmel/ATSTK1000/target_skeleton/etc/init.d/S43ntp
+++ b/target/device/Atmel/ATSTK1000/target_skeleton/etc/init.d/S43ntp
@@ -1,36 +1,37 @@
 #!/bin/sh
 
-NTPDATE=`which ntpdate`
-NTPD=`which ntpd`
+NTPDATE=/usr/bin/ntpdate
+NTPD=/usr/sbin/ntpd
 
 if [ -f /etc/default/ntpdate ]; then
     . /etc/default/ntpdate
+else
+	echo " missing /etc/default/ntpdate"
+	exit 1
 fi
 
-echo -n " * running ntpdate ...           "
-if [ ! -x "${NTPDATE}" ]; then
-	echo "[ MISSING ]"
+echo -n "Starting ntpdate:"
+if [ ! -x ${NTPDATE} ]; then
+	echo " missing"
 	exit 1
 fi
 
 if ${NTPDATE} $NTPOPTIONS $NTPSERVERS > /dev/null 2> /dev/null; then
-	echo "[ OK ]"
+	echo " done"
 else
-	echo "[ FAILED ]"
+	echo " failed"
 	exit 1
 fi
 
-echo -n " * starting ntpd ...             "
-if [ ! -x "${NTPD}" ]; then
-	echo "[ MISSING ]"
+echo -n "Starting ntpd:"
+if [ ! -x ${NTPD} ]; then
+	echo " missing"
 	exit 1
 fi
 
 if ${NTPD} > /dev/null 2> /dev/null; then
-	echo "[ OK ]"
+	echo " done"
 else
-	echo "[ FAILED ]"
+	echo " failed"
 	exit 1
 fi
-
-exit 0
