Fix bpp settings in fb and initialize properly on startup for Atmel target ATSTK1000
Signed-off-by: Hans-Christian Egtvedt <hcegtvedt@atmel.com>

diff --git a/target/device/Atmel/ATSTK1000/target_skeleton/etc/init.d/S03bootsplash b/target/device/Atmel/ATSTK1000/target_skeleton/etc/init.d/S03bootsplash
--- a/target/device/Atmel/ATSTK1000/target_skeleton/etc/init.d/S03bootsplash
+++ b/target/device/Atmel/ATSTK1000/target_skeleton/etc/init.d/S03bootsplash
@@ -1,18 +1,26 @@
 #!/bin/sh
 
-PROGRAM=/usr/bin/fbv
+FBV=/usr/bin/fbv
+FBSET=/usr/sbin/fbset
+FBMODEFILE="/etc/fb.modes"
 SPLASHFILE="/etc/stk1000bootsplash.jpg"
 
 echo -n "Bootsplash image:"
-if [ ! -x "${PROGRAM}" -o ! -f "${SPLASHFILE}" ]; then
+if [ ! -x "${FBV}" -o ! -x "${FBSET}" -o \
+		! -f "${SPLASHFILE}" -o ! -f "${FBMODEFILE}" ]; then
 	echo " missing"
 	exit 1
 fi
 
-${PROGRAM} ${SPLASHFILE} < /dev/null > /dev/null 2>/dev/null &
+if ! ${FBSET} 320x240-68 > /dev/null 2> /dev/null; then
+	echo " failed"
+	exit 1
+fi
+
+${FBV} ${SPLASHFILE} < /dev/null > /dev/null 2> /dev/null &
 if [ $? -eq 0 ]; then
 	echo " loaded"
-	kill `pidof ${PROGRAM}` > /dev/null 2> /dev/null
+	kill `pidof ${FBV}` > /dev/null 2> /dev/null
 else
 	echo " failed"
 fi
